    POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name":" myname",
    "lastName": " afaga",
    "username" : " agaga" ,
    "email":"afafadfadf4@1.com",
    "password":"pasordfafa"

}                   