    POST http://localhost:3000/auth/register
Content-Type: application/json

{
 
     "username" : " tss" ,
    "email":"afafadfafaasfdasc@a.om",
    "password":"agaga@paZA12"

}                       